name: SonarCloud Analysis
on: [push, pull_request]

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Change this if your project uses another version
      - name: List files in target/classes (Debugging)
        run: ls -R target/classes || echo "Directory not found"
      - name: Show directory structure
        run: ls -R
      - name: Build with Maven
        working-directory: MachinationsServer  # Change this if `pom.xml` is inside a different folder
        run: mvn -X clean compile
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=911-calota-ovidiu
            -Dsonar.projectKey=911-Calota-Ovidiu_Bachelors_Backend
            -Dsonar.java.binaries=MachinationsServer/target/classes
